Handle test failures where 'err.name' and 'err.stack' are undefined
webdriverio/wdio-allure-reporter pull request #161
Opened 2019-07-07 22:51 UTC by robwalch

This is a patch for v0.8.3. The reporter throws an exception when encountering failures with errors missing a `name` and `stack` property (like cucumber-js's "Multiple step definitions match" error).

```js
{ event: 'test:fail',
  type: 'test',
  file: '../x.feature',
  err: { message: 'Multiple step definitions match:\n...' },
```

2019-08-02 12:45 UTC, robwalch commented
@BorisOsipov Can a maintainer please review?

2019-08-28 10:21 UTC, BorisOsipov approved these changes

2019-08-28 10:45 UTC, christian-bromann requested changes

2019-08-28 10:45 UTC, christian-bromann commented on lib/utils.js
> +        var stackTrace = test.err.stack.trim()
```suggestion
        const stackTrace = test.err.stack.trim()
```

2019-08-28 10:46 UTC, christian-bromann commented
@robwalch we recommend to switch to v5, we don't maintain v4 services and reporters anymore

2019-08-28 12:55 UTC, robwalch commented
@christian-bromann we just made the switch. Thanks!

2019-08-28 12:55 UTC, closed without merging